services:

  mysql:
      image: mysql:latest
      restart: always
      env_file:
        - .env
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASSWORD}
      ports:
        - "3306:3306"
      volumes:
        - mysql:/var/lib/mysql
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 10s
        retries: 3
        start_period: 30s
volumes:
  mysql: